package jogo.logica.Enum;

public enum Situacao {

     INICIO,
     ESCOLHEOPCAO,
     ESCOLHENUMEROJOGADORES,
     AGUARDAJOGADA,
     INSERENOMES,
     AGUARDAJOGADAAVANCADA,
     TERMINAJOGO,
     JOGAMINIJOGO,
     JOGAMINIJOGOMATEMATICA,
     JOGAMINIJOGOPALAVRAS,
     ASSISTEREPLAYS;
}
